events {}

http {
    server {
        listen 80;
        server_name okinawaaaaaaaaaaaaws.com;

        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name okinawaaaaaaaaaaaaws.com;

        ssl_certificate /etc/letsencrypt/live/okinawaaaaaaaaaaaaws.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/okinawaaaaaaaaaaaaws.com/privkey.pem;

        location / {
            proxy_pass http://app:8000;
        }
    }
}